# Generated by Django 4.0.8 on 2024-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_code',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
